# Generated by Django 4.2.30 on 2026-07-28 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase"),
                            ("SALE", "Sale"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("balance_after", models.IntegerField()),
                ("movement_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reference_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-movement_date"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_stock", models.IntegerField(default=0)),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("last_stock_update", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Low Stock", "Low Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_record",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
